/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'accessories' : null } |
  { 'dresses' : null } |
  { 'mens' : null } |
  { 'tops' : null } |
  { 'bottoms' : null } |
  { 'shoes' : null } |
  { 'womens' : null };
export interface OrderItem { 'quantity' : bigint, 'product' : Product }
export type OrderStatus = { 'shipped' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface OrderT {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'imageUrl' : string,
  'category' : Category,
  'price' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, number, string, Category], undefined>,
  'getCategoryByString' : ActorMethod<[string], Category>,
  'getOrder' : ActorMethod<[bigint], OrderT>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'initializeProducts' : ActorMethod<[], undefined>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], bigint>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];