/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'accessories' : IDL.Null,
  'dresses' : IDL.Null,
  'mens' : IDL.Null,
  'tops' : IDL.Null,
  'bottoms' : IDL.Null,
  'shoes' : IDL.Null,
  'womens' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'price' : IDL.Float64,
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const OrderT = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Float64, IDL.Text, Category], [], []),
  'getCategoryByString' : IDL.Func([IDL.Text], [Category], []),
  'getOrder' : IDL.Func([IDL.Nat], [OrderT], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'initializeProducts' : IDL.Func([], [], []),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [IDL.Nat], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'accessories' : IDL.Null,
    'dresses' : IDL.Null,
    'mens' : IDL.Null,
    'tops' : IDL.Null,
    'bottoms' : IDL.Null,
    'shoes' : IDL.Null,
    'womens' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const OrderItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const OrderT = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, Category],
        [],
        [],
      ),
    'getCategoryByString' : IDL.Func([IDL.Text], [Category], []),
    'getOrder' : IDL.Func([IDL.Nat], [OrderT], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'initializeProducts' : IDL.Func([], [], []),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [IDL.Nat], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };